### ISSUE TITLE
Build on BSD is broken

### ISSUE THREAD

**Issue by avysk** [Goddard-Fortran-Ecosystem/gFTL#103]
BSD `m4` behaves differently from GNU `m4`. If `m4` is hardcoded, the results of build are wrong (e.g. `__type_MOVE` is generated instead of `__TYPE_MOVE`). The proposed fix is in https://github.com/Goddard-Fortran-Ecosystem/gFTL/pull/102

**Comment by tclune** [comment]
Fixed in #102
