### ISSUE TITLE
vector and deque erase_range on empty range calls MOVE_ALLOC(X, X)

### ISSUE THREAD

**Issue by jeanPerier** [Goddard-Fortran-Ecosystem/gFTL#211]
There is a test (see [[1]](https://github.com/Goddard-Fortran-Ecosystem/gFTL/blob/dc93a5fc2fe2b487590580d9f0a17d77ca3fe5c1/tests/vector/Test_Vector.m4#L409)) for vector and deque that calls `erase_range(iterator, iterator)` (empty range). This currently ends-up calling `MOVE_ALLOC(X, X)` (at [[2]](https://github.com/Goddard-Fortran-Ecosystem/gFTL/blob/dc93a5fc2fe2b487590580d9f0a17d77ca3fe5c1/include/v2/deque/procedures.inc#L743) and [[3]](https://github.com/Goddard-Fortran-Ecosystem/gFTL/blob/dc93a5fc2fe2b487590580d9f0a17d77ca3fe5c1/include/v2/vector/procedures.inc#L777)) which is not legal Fortran (see [4]).
While most compilers do not emit runtime errors, they silently deallocate X, which in the case of  erase_range ends-up destroying the vector/deque elements after the iterator. I expect the intention for `erase_range(iterator, iterator)`  is to be a no-op instead, the vector/deque code should probably do nothing in this case.

You can observe the issue if you add an ASSERT to test the element values (like `ASSERT(v%at(2), two)`) after the `erase_range` call in the `test_erase_empty_range` test.

gfortran builds will fail with:

```
[Test_deferred_stringVector.pf:851]
String assertion failed:
    expected: <"">
   but found: <"two">
  first diff: 
```

[1] : https://github.com/Goddard-Fortran-Ecosystem/gFTL/blob/dc93a5fc2fe2b487590580d9f0a17d77ca3fe5c1/tests/vector/Test_Vector.m4#L409
[2]: https://github.com/Goddard-Fortran-Ecosystem/gFTL/blob/dc93a5fc2fe2b487590580d9f0a17d77ca3fe5c1/include/v2/deque/procedures.inc#L743
[3]: https://github.com/Goddard-Fortran-Ecosystem/gFTL/blob/dc93a5fc2fe2b487590580d9f0a17d77ca3fe5c1/include/v2/vector/procedures.inc#L777
[4]:  Fortran 2018 section 16.9.137 point 4 mandates: "if FROM and TO are the same variable, it shall be unallocated when MOVE_ALLOC is invoked"

I found this issue because flang generate runtime errors for such MOVE_ALLOC.

**Comment by tclune** [comment]
Ah - I don't think the problem is the use of `MOVE_ALLOC` per se.  Rather the code should never go into the following loop when `delta` is 0:
https://github.com/Goddard-Fortran-Ecosystem/gFTL/blob/dc93a5fc2fe2b487590580d9f0a17d77ca3fe5c1/include/v2/deque/procedures.inc#L737-L745

The loop is meant to shift the elements but when the shift is 0, the loop is shifting each element on top of itself.

So maybe a bit more than one line, but still a simple fix in a few places.
