### ISSUE TITLE
gFTL installs spurious "Foo" includes

### ISSUE THREAD

**Issue by olebole** [Goddard-Fortran-Ecosystem/gFTL#96]
In `include/types`, gFTL installs the files `Foo.inc`, `FooPoly.inc`, `FooPolyPtr.inc`, and `FooPtr.inc`.
These require modules which are not available: 
```
use Foo_mod, only: Foo
```
This looks like example files; shouldn't they be installed as examples?

**Comment by tclune** [comment]
Not examples, per se, though that might be a good idea.   They were introduced in the early days for testing the functionality with derived types.   Testing became more sophisticated later on and these are duplicated in the tests/include/types where there is a Foo module.

I've just pushed a fix that eliminates these, but have only done a very quick test.    I will now merge with develop.  Let me know if you need a formal release.

**Comment by olebole** [comment]
I can also remove them manually in the Debian package, no problem.
BTW, I am not sure whether I already said that I am going to create official Debian packages for it. Announcement [here](http://bugs.debian.org/961670). Similarly for [gftl-shared](http://bugs.debian.org/961669), [fargparse](http://bugs.debian.org/961668) and [pfunit](http://bugs.debian.org/961667).

**Comment by tclune** [comment]
Cool!  If you did mention it before, I missed it. 

Thanks!
